Add action to get/create/delete zone access rule
StackStorm-Exchange/stackstorm-cloudflare pull request #11
Opened 2022-03-21 21:08 UTC by rogeriobastos

This PR add 3 new action:
* `create_zone_access_rule` - create a firewall access rule for a zone
* `delete_zone_access_rule`- delete a firewall access rule from a zone
* `get_zone_access_rule` - list/search firewall access rule in a zone

Also, it adjusts `lib/actions.py` to allow do POST requests.

2022-03-22 12:29 UTC, armab commented
@StackStorm-Exchange/encoretechnologies Can you folks please help reviewing this?

2022-03-23 05:47 UTC, bishopbm1 requested changes
Thank you for the PR! Just needs some unit tests and please add to the ChangeLog and bump the version in the pack.yaml file.

2022-03-23 05:47 UTC, bishopbm1 commented on actions/lib/actions.py
> +            if func.__name__ == 'post':
Would like to see 2 tests to show the different conditions are being executed as expected. https://github.com/StackStorm-Exchange/stackstorm-cloudflare/blob/master/tests/test_action_base.py

2022-05-11 12:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/StackStorm-Exchange/stackstorm-cloudflare?pullRequest=11) <br/>All committers have signed the CLA.

2022-05-11 16:20 UTC, rogeriobastos commented on actions/lib/actions.py
> +            if func.__name__ == 'post':
Sorry for the delay, I was on vacation. I'll look at this soon.

2026-03-30 12:24 UTC, closed without merging